- README.md
- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/slack-notifier.go
Slack doesn't appear to give out tokens anymore for webhooks, but instead generates a url to use.
> Use new slack incoming-webhook url

- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/slack-notifier.go
Hi, I have made a more stylish slack alert format.
Set `consul-alerts/config/notifiers/slack/detailed` to `true` to enable this.
> More visible output in consul slack alerts

- consul-alerts.go
Before:
```
$ curl 0:9000/v1/info -qvs 2>&1 | grep '<'
< HTTP/1.1 201 Created
< Date: Mon, 29 Jun 2015 16:36:03 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
```
After:
```
$ curl 0:9000/v1/info -qvs 2>&1 | grep '<'
< HTTP/1.1 201 Created
< Version: Consul Alerts 0.3.0
< Date: Mon, 29 Jun 2015 17:30:32 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
```
> Add the `version` header before flushing response

- consul/client.go
If I blacklist other nodes, I no longer receive notifications for the health checks I do care about.
> Fix health checks not being processed if any blacklisted

- notifier/opsgenie-notifier.go
The OpsGenie go sdk changed its interface w/ this change:
https://github.com/opsgenie/opsgenie-go-sdk/commit/d2a50423187d552340874644ed9ff3b43252a871
> Fix OpsGenie client.SetAPIKey()

- consul-alerts.go
- consul/client.go
- consul/interface.go
- leader-election.go
- notifier/opsgenie-notifier.go
Hi, we have had some issues of consul-alerts request swamping consul when consul-alerts and consul come up simultaneously on a new cluster.  In our system the daemonized consul-alerts will immediately try again and again if consul is still electing leader and end up interfering.  So I added 10 second sleeps to both consul and consul-alert leader elections.  For the consul, it also tries ten times before giving up.
I believe these should improve leader election.
In addition, I added log level support.  Right now it appears everything goes to INFO and it is quite chatty about mundane things like not being the leader.  In general logs need assigned better classification and multiples should be suppressed.  Anyway, this allows a temporary fix of setting the log level higher.
> Add logging and sleeps for leader election

- README.md
- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/hipchat-notifier.go
This is an attempt at making it so we can pass the ["from" option](https://github.com/tbruyelle/hipchat-go/blob/9415f35af77982a56e08b861cfdb4f0263017d9b/hipchat/room.go#L78) supported by hipchat-go.  Right now, if I create an auth token in hipchat, then all the messages from consul-alerts show up as being from "Jason Walton", because this is the name associated with my account.  By providing the from option, we should be able to get these to show up as, for example, "Consul Alerts".
Before you read this, though: this is my first ever attempt at writing a line of go, so be forewarned.  :P  I also couldn't figure out how to build this, so it might not even compile.  I tired `make`, which gave me quite a few errors along the lines of:
```
check-handler.go:11:2: cannot find package …
```
> Add support for 'from' for hipchat notifier.

- notifier/opsgenie-notifier.go
When an alert is filtered by opsgenie, it didnt send an response. Because of that consult alert crash.
> Avoid nil exception when the response from opsgenie is empty

- check-handler.go
- notifier/notifier.go
With the previous method after time offline the service would send at every reminder interval for a time until the interval count caught up.
> Improves reminders to prevent extra alerts after outage

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
We’d like to start opening up `consul-alerts` to more contributors to the project.
This is an initial set of documents to outline how to contribute and the community code of conduct. It serves as a start for opening up the project.
Unless there are any strong objections, we’ll merge this PR and can then edit or extend as the community grows.
> Initial CONTRIBUTING and CODE_OF_CONDUCT docs

- README.md
Prompted by #103, some additions to the doco for the HipChat notifier so it is clear that the auth token needs to be a room notification token for the room the notifications are being sent to. Also that there is a default value for the base URL.
> Improved HipChat notifier documentation.

- README.md
- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/email-notifier.go
Functionality should remain unchanged unless the new config option is used.
Our sysadmins weren't happy with receiving emails with info about multiple nodes in, so added a little bit of logic to separate it out.
Any thoughts / comments appreciated as I'm still trying to learn Golang
Cheers,
> Added config option to send one email per node rather than all nodes in one email

- consul-alerts.go
- consul/client.go
- consul/interface.go
- health-wildcard-handler.go
Extend `consul-alerts` API with `v1/health/wildcard`, which are similiar to `v1/health` but return all matched checks (omitted service/node/check params assumed as `any`) . Values returned in JSON form,  status code 503 if one of services in critical state.
Additional params to `ignoreBlacklist`, and `alwaysOk` (last one force status code to 200 disregarding checks status)
> Add wildcard query API

- Dockerfile
The Docker image currently doesn't build in `master` because `runtime/cgo` (which seems to be at the end of a dependency chain started by a bunch of AWS packages?) needs `gcc` installed, which doesn't exist in the default Alpine Linux package.  This patch installs it in the Docker image before compilation of `consul-alerts` and then uninstalls it to keep the image size reasonable.
> Install alpine-sdk for build in Docker image

- README.md
- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/notifier.go
- notifier/victorops-notifier.go
Adds a VictorOps notifier by directly hitting the VictorOps API (documentation at http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/).  Fulfills the feature request at https://github.com/AcalephStorage/consul-alerts/issues/71.  This will compile and run locally fine, but note that Docker images don't seem to currently be building in master (nor in this PR) because of an unrelated missing build dependency; I've submitted a separate PR at https://github.com/AcalephStorage/consul-alerts/pull/128 to fix that.
> Add VictorOps notifier

- Dockerfile
- README.md
- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/email-notifier.go
- notifier/hipchat-notifier.go
- notifier/notifier.go
- notifier/opsgenie-notifier.go
- notifier/victorops-notifier.go
- provision/consul-server.conf.j2
- provision/site.yml
I just adapted the code in order to:
- Accept consul-alerts options in JSON config file.
- The options in config file will overwrite the options in command line.
Hope that this one doesn't disturb the current code and is accepted. 
I have tested on our system. It is highly appreciated if anyone can let me know what I need to improve. 
Thank you.
> Configure consul-alerts options by using JSON file

- notifier/email-notifier.go
Some of the checks change the cluster name to display differing information in the subject line
> Ensure the cluster name is the one from the individual email

- consul-alerts.go
As suggested in #152, printing ACL token to logs might lead to security issues. In this PR it is removed from the output.
> Drop ACL token from logs

- consul/client.go
Addresses one of scalability issues per https://github.com/AcalephStorage/consul-alerts/issues/57
By default, we do 4 GET requests against blacklist in the KV for each health check every 10s. If you have 1000 checks, it is 4000 requests even if you do not maintain any blacklists. This PR makes the function to return as soon as a match is found or immediately if there is no blacklist at all.
> Improve checking against blacklist by reducing the number of calls to KV

- consul/client.go
When the new healthcheck is registered and its status is `passing`, it is still marked for notification because there is a status change (from ` ` to `passing`).
With this PR, fresh passing checks are not marked for notification.
> do not trigger a notification if the new healthcheck is passing

- notifier/aws-sns-notifier.go
NotifName returns 'awsns' string and should return 'awssns'
> Fixes return string for NotifierName() method on AwsSnsNotifier struct

- notifier/slack-notifier.go
In Slack, single backticks are only applied to single line text and are treated as part of text when there is more than one line.   Triple backticks can be used to format one or more lines.
> Use better format for multi-line messages

- consul-alerts.go
Release notes:
**MAIN IMPROVEMENTS**
* Specific change-threshold for node/service/check (#186)
* Better format for multi-line messages (#185)
* Notifications are not triggered if the new healthcheck is passing (#169)
* Number of calls to KV is reduced when checking against blacklist (#167)
* Number of unnecessary writes (PUT requests) to KV is reduced when there is no change in health check status (#166)
* Support for mattermost notifications (#165)
* Variable overrides and profile selection based on regular expressions (#164)
* ACL token is not shown in the logs (#160)
* Backtips are not prined for empty slack messages (#151)
and numerous bug fixes.
I hope I did not forget anything.
@fusiondog  Can I kindly ask you to review and merge it after #188 and then cut the release?
Thank you in …
> Release 0.5.0

- README.md
- consul/client.go
- consul/interface.go
- notifier/aws-sns-notifier.go
- notifier/aws-sns-notifier_test.go
- notifier/email-notifier.go
- notifier/templating.go
- notifier/templating_test.go
This PR introduces templating functionality for the body sent by the SNS notifier. 
It's designed to function like the templating mechanism of the E-Mail notifier and reuses a lot of its code. To conform to the same interface, this PR also adds the `clusterName` attribute to the SNS notifier. 
I wasn't sure how much you cared about compatibility so I stayed conservative here at the expense of consistency: By default, the notifier behaves as before, not including a clusterName. The clusterName can be used in custom templates though. This is different from other notifiers that set a default cluster-name and include it in default messages. Let me know if you prefer a different solution.
> Add sns templating

- notifier/slack-notifier.go
- notifier/slack_notifier_test.go
Problem: It's not possible to override the cluster name in Slack integration using `VarOverrides` object present in each `notif-profile`. The app will just ignore any `cluster_name` key present on `VarOverrides` on the selected profile and will use the default cluster name configured in the `notifier`.
This PR is intended to allow this kind of override as it will simplify the configuration in some use cases using only one slack `notifier` and override the cluster name in the corresponding `notif-profiles`
> Enable cluster name override on slack integration

- check-handler.go
Solves #198.
Currently, if the health check is blacklisted and it fails, there is no alert or reminder created. If the health check fails and then it is blacklisted, there can exist a reminder that will keep alerting.
```
$ consul agent -dev
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
Version: 'v0.7.5'
Node ID: 'fb2170a8-257d-3c64-b14d-bc06cc94e34c'
Node name: 'Aleksandrs-MacBook-Pro.local'
Datacenter: 'dc1'
Server: true (bootstrap: false)
Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
Atlas: <disabled>
==> Log data will now stream in as it occurs:
...
$ nomad agent -dev
No configuration files loaded
==> Starting Nomad …
```
> Delete a reminder if the corresponding healthcheck is blacklisted

- consul/client.go
After a network failure, we managed to get a hanging reminder in Consul-Alerts. The reminders looked like this:
```json
{"Node":"Aleksandrs-MacBook Pro.local",
"ServiceId":"",
"Service":"",
"CheckId":"serfHealth",
"Check":"Serf Health Status",
"Status":"critical",
"Output":"Agent alive and reachable",
"Notes":"","Interval":300,
"RmdCheck":"2017-07-11T08:49:44.378586605+02:00",
"NotifList":{"email":true},
...
}
```
The health check that initially triggered the reminder was already passing, but the reminder still existed. **NB** its inconsistent state where the status is critical, but according to the output the agent is alive and reachable.
The problem was caused by a race condition between `consul/client.UpdateCheckData` ([#L346](https://github.com/AcalephStorage/consul-alerts/blob/master/ …
> Update reminder state with CAS instead of Put

- README.md
- consul-alerts.go
- consul/client.go
- consul/interface.go
- notifier/mattermost-webhook-notifier.go
- notifier/mattermost-webhook-notifier_test.go
- notifier/notifier.go
- notifier/slack_notifier_test.go
- send-notifs.go
> Notify Mattermost via Incoming Webhooks

- README.md
- consul/client.go
- notifier/pagerduty-notifier.go
- notifier/pagerduty_notifier_test.go
* add MaxRetries and RetryBaseInterval to pagerduty notifier
* read those values from Consul on start
* set values on client if configured
* add tests of client with / without MaxRetries, RetryBaseInterval
* README: add new items in PagerDuty section
> Implement retry configs for pagerduty notifier

- Makefile
ATM nomad is unable to unarchive the `.tar` distribution. See https://github.com/hashicorp/go-getter/issues/19 and https://github.com/hashicorp/nomad/issues/2443 for history on the topic. This update allows nomad to use go-getter to download and run consul-alerts. While I would prefer nomad be updated to support `.tar`, it's been years, and we haven't seen that happen.
> publish/distribute consul-alerts as a compressed .tgz

- consul-alerts.go
- watchers.go
To make watchers support Consul ACL, I added token in argument of consul watch command.  
Of course I know that consul-alerts supports ACLs, but since consul-alerts do not pass token as an argument to the consul watch command, we can only use the default ACL token.  
Therefore, I think that it is better to change to explicitly pass token to consul watch command.  
ref. https://www.consul.io/docs/agent/watches.html#token
> Added token in argument of consul watch command
