AcalephStorage/consul-alerts

notifier/slack-notifier.go
Added check output when notify to slack. so i think almost everyone wants it.
=> add check output slack notification.

watchers.go
When `consul` is not found in `$PATH`, `cmd.Run()` returns `*exec.Error`, not `*exec.ExitError`.
So current error handling logic is not a enough one, then I fixed.
=> Make handling cmd.Run() errors stable

README.md
=> Fix example errors

check-handler.go, consul-alerts.go, event-handler.go, send-notifs.go
=> Refactor notif

Dockerfile
fix for AcalephStorage/consul-alerts#55
=> add consul to the docker container

notifier/opsgenie-notifier.go
This should allow the project to compile, right now it is throwing an error for me on this.
=> SetApiKey should be SetAPIKey

README.md, check-handler.go, consul-alerts.go, consul/client.go, consul/interface.go, notifier/email-notifier.go, notifier/hipchat-notifier.go, notifier/influxdb-notifier.go, notifier/log-notifier.go, notifier/notifier.go, notifier/opsgenie-notifier.go, notifier/pagerduty-notifier.go, notifier/slack-notifier.go, send-notifs.go
This code adds the ability to set profiles to define reminder intervals and notifier selection.
=> Profiles and reminders

README.md, consul-alerts.go, consul/client.go, consul/interface.go, notifier/aws-sns-notifier.go
feature requested in issue #14
=> aws sns support

consul/client.go
This addresses the bug in https://github.com/AcalephStorage/consul-alerts/issues/96
=> Fixes runtime error with custom notifiers.

README.md
Addresses clarity concerns in https://github.com/AcalephStorage/consul-alerts/issues/97
=> Clarifying docs on profiles and reminders.

README.md
Addresses document clarity issues in #102
=> Adds notes on failover and config loading.

notifier/email-notifier.go, notifier/email-notifier_test.go
=> Fixes AcalephStorage/consul-alerts#114

notifier/hipchat-notifier.go
Make the HipChat notifier generate HTML-formatted notifications.
=> Improve hipchat notifier

Dockerfile
Drastically reduce the Docker image size.
=> reduce Docker image size from 800MB to 18MB

consul/client.go
Addresses one of scalability issues per https://github.com/AcalephStorage/consul-alerts/issues/57
By default, we run at least 1 PUT to KV for each health check every 10s even the status is unchanged. If you have 1000 checks, it is 1000 PUT requests additionally. This PR prevents unnecessary writes (PUT requests) to KV when no change in health check status.
=> Reduce unnecessary writes (PUT requests) to KV when no change in health check status

README.md
Added documentation for enabling Slack "detailed" notification mode.
=> Document Slack detailed config

.travis.yml, Vagrantfile, provision/consul-server.conf.j2
With this PR Travis automatically picks the dependencies and also runs tests
=> Travis picks dependencies and runs tests

README.md
Added ACL policy config needed in ACL enabled cluster.
=> Configuration: ACL example

README.md
Because of issue #187
It took me a while to realise this.
=> Giving clearer examples on slack setup

consul/client.go, consul/client_test.go
=> Trim config parameters

.travis.yml, provision/consul-server.conf.j2, provision/site.yml
Since we heavily rely on the behavior of Consul API, IMO it makes sense to test against multiple Consul versions.
@fusiondog  what do you think?
=> Test in travis against multiple versions of Consul

notifier/slack-notifier.go, notifier/slack_notifier_test.go
This is a fix for the issue https://github.com/AcalephStorage/consul-alerts/issues/251
=> enable the url, detailed and enabled json tags

consul/client.go, consul/client_test.go
This the fix for the issue: https://github.com/AcalephStorage/consul-alerts/issues/248
=> fix the panic when the reminders dir in consul-alerts has no sub-folders

notifier/pagerduty-notifier.go
=> change pagerduty notifier to use a human readable description

notifier/http-endpoint-notifier.go
Most of the HTTP Endpoints are expecting application/json requests. This pull request wants to make it right. Looking forward we might or might not want to make this a configurable choice.
In case we do, I'd be happy to open another pull request.
=> POSTing with http-endpoint as application/json instead of application/x-www-form-urlencoded
